# Generated by Django 2.0.5 on 2018-05-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180519_2216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
